# Generated by Django 5.1.5 on 2025-01-29 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('responsible_roles', models.CharField(default='program_officers', help_text="Comma-separated roles responsible for this department, e.g., 'specialists'", max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('students', 'Students'), ('program_officers', 'Program Officers'), ('specialists', 'Specialists'), ('others', 'Others')], default='students', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tickets.department'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=20)),
                ('assigned_department', models.CharField(choices=[('general_enquiry', 'General Enquiry'), ('academic_support', 'Academic Support'), ('health_services', 'Health Services'), ('financial_aid', 'Financial Aid'), ('career_services', 'Career Services'), ('welfare', 'Welfare'), ('misconduct', 'Misconduct'), ('it_support', 'IT Support'), ('housing', 'Housing and Accommodation'), ('admissions', 'Admissions'), ('library_services', 'Library Services'), ('research_support', 'Research Support'), ('study_abroad', 'Study Abroad'), ('alumni_relations', 'Alumni Relations'), ('exam_office', 'Examinations Office'), ('security', 'Campus Security'), ('language_centre', 'Language Centre')], default='general_enquiry', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_action', models.CharField(blank=True, choices=[('created', 'Created'), ('status_updated', 'Status Updated'), ('priority_updated', 'Priority Updated'), ('redirected', 'Redirected'), ('responded', 'Responded'), ('closed', 'Closed')], max_length=20, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'specialists'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL)),
                ('latest_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('status_updated', 'Status Updated'), ('priority_updated', 'Priority Updated'), ('redirected', 'Redirected'), ('responded', 'Responded'), ('closed', 'Closed')], max_length=100)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_taken_by', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
            ],
        ),
    ]
