# Generated by Django 5.1.5 on 2025-02-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_department_user_role_user_department_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
