# Generated by Django 5.1.5 on 2025-02-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_sender_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assigned_to',
            new_name='assigned_user',
        ),
    ]
