# Generated by Django 5.1.5 on 2025-02-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_answers'),
        ('tickets', '0004_rename_assigned_to_ticket_assigned_user'),
    ]

    operations = [
    ]
