# Generated by Django 5.1.5 on 2025-02-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_merge_20250208_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='answers',
        ),
    ]
