# Generated by Django 5.1.5 on 2025-02-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answers',
            field=models.TextField(blank=True, help_text='All responses to the ticket.', null=True),
        ),
    ]
