# Generated by Django 5.1.5 on 2025-02-15 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITicketProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_generated_response', models.TextField(blank=True, help_text='AI-generated response for review.', null=True)),
                ('ai_assigned_department', models.CharField(choices=[('general_enquiry', 'General Enquiry'), ('academic_support', 'Academic Support'), ('health_services', 'Health Services'), ('financial_aid', 'Financial Aid'), ('career_services', 'Career Services'), ('welfare', 'Welfare'), ('misconduct', 'Misconduct'), ('it_support', 'IT Support'), ('housing', 'Housing and Accommodation'), ('admissions', 'Admissions'), ('library_services', 'Library Services'), ('research_support', 'Research Support'), ('study_abroad', 'Study Abroad'), ('alumni_relations', 'Alumni Relations'), ('exam_office', 'Examinations Office'), ('security', 'Campus Security'), ('language_centre', 'Language Centre')], default='general_enquiry', help_text='AI-suggested department classification.', max_length=50)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processing', to='tickets.ticket')),
            ],
        ),
    ]
