# Generated by Django 5.1.6 on 2025-02-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_ticket_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="return_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                    ("returned", "Returned"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
