# Generated by Django 5.1.6 on 2025-02-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_return_reason_alter_ticket_status'),
        ('tickets', '0009_merge_0008_aiticketprocessing_0008_response'),
    ]

    operations = [
    ]
