# Generated by Django 5.1.5 on 2025-02-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_latest_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiticketprocessing',
            name='ai_assigned_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', help_text='AI-suggested priority level.', max_length=20),
        ),
    ]
