# Generated by Django 5.1.5 on 2025-03-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_aiticketprocessing_ai_assigned_priority'),
        ('tickets', '0012_alter_ticketattachment_file'),
    ]

    operations = [
    ]
