# Generated by Django 5.1.2 on 2025-03-09 02:46

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_merge_20250303_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to=tickets.models.user_directory_path),
        ),
    ]
