# Generated by Django 5.1.5 on 2025-03-08 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_merge_20250303_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('primary_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_ticket', to='tickets.ticket')),
                ('suggested_merged_tickets', models.ManyToManyField(related_name='suggested_merged_tickets', to='tickets.ticket')),
            ],
        ),
    ]
