# Generated by Django 5.1.5 on 2025-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_mergedticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedticket',
            name='approved_merged_tickets',
            field=models.ManyToManyField(related_name='approved_merged_tickets', to='tickets.ticket'),
        ),
    ]
