# Generated by Django 5.1.5 on 2025-03-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_ticket_status'),
        ('tickets', '0015_mergedticket_approved_merged_tickets'),
    ]

    operations = [
    ]
