# Generated by Django 5.1.5 on 2025-03-12 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_merge_20250312_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTicketClosureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('department', models.CharField(choices=[('general_enquiry', 'General Enquiry'), ('academic_support', 'Academic Support'), ('health_services', 'Health Services'), ('financial_aid', 'Financial Aid'), ('career_services', 'Career Services'), ('welfare', 'Welfare'), ('misconduct', 'Misconduct'), ('it_support', 'IT Support'), ('housing', 'Housing and Accommodation'), ('admissions', 'Admissions'), ('library_services', 'Library Services'), ('research_support', 'Research Support'), ('study_abroad', 'Study Abroad'), ('alumni_relations', 'Alumni Relations'), ('exam_office', 'Examinations Office'), ('security', 'Campus Security'), ('language_centre', 'Language Centre')], max_length=50)),
                ('closed_by_inactivity', models.PositiveIntegerField(default=0)),
                ('closed_manually', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='mergedticket',
            name='primary_ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_ticket', to='tickets.ticket'),
        ),
    ]
