# Generated by Django 5.1.5 on 2025-03-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_ticket_id_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='can_be_managed',
            field=models.BooleanField(default=True, help_text='Whether the ticket can be managed by the current user.'),
        ),
    ]
