# Generated by Django 5.1.5 on 2025-03-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_ticket_can_be_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='need_student_update',
            field=models.BooleanField(default=False, help_text='Whether the ticket needs an update from the student.'),
        ),
    ]
