# Generated by Django 5.1.5 on 2025-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0021_alter_ticket_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyticketclosurereport",
            name="in_progress",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="dailyticketclosurereport",
            unique_together={("date", "department")},
        ),
    ]
