# Generated by Django 5.1.7 on 2025-03-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_dailyticketclosurereport_in_progress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='can_be_managed',
            new_name='can_be_managed_by_program_officers',
        ),
        migrations.AddField(
            model_name='ticket',
            name='can_be_managed_by_specialist',
            field=models.BooleanField(default=True, help_text='Whether the ticket can be managed by the current user.'),
        ),
    ]
