# Generated by Django 5.1.6 on 2025-03-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_merge_20250313_1150'),
        ('tickets', '0018_alter_mergedticket_primary_ticket'),
        ('tickets', '0023_rename_can_be_managed_ticket_can_be_managed_by_program_officers_and_more'),
    ]

    operations = [
    ]
