# Generated by Django 5.1.6 on 2025-03-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_ticket_can_be_managed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='can_be_managed',
        ),
    ]
