# Generated by Django 5.1.6 on 2025-03-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_remove_ticket_can_be_managed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='program_officer_resolved',
            field=models.BooleanField(default=False, help_text='Whether the program officer has resolved the ticket.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='specialist_resolved',
            field=models.BooleanField(default=False, help_text='Whether the specialist has resolved the ticket.'),
        ),
    ]
