# Generated by Django 5.1.7 on 2025-03-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_merge_20250320_1810'),
        ('tickets', '0026_ticket_program_officer_resolved_and_more'),
    ]

    operations = [
    ]
